### ISSUE TITLE
Can't spawn multiple car

### ISSUE THREAD

**Issue by ItsikNox** [esx-overextended/es_extended#58]
Hello,

I'm not sure if it's just me or not, but if I spawn a vehicle with a /car or through ESX.CreateVehicle I can't create a second one.

I don't get any errors and if I print the data of the vehicle I'm trying to create, it appears but the vehicle doesn't spawn, unless I delete the first vehicle that spawned.

**Comment by mahanmoulaei** [comment]
Hey,
I made some changes in the last couple of days and everything is currently stable.
I just used the [recipe](https://github.com/esx-overextended/txAdminRecipe) and setup a fresh server. Vehicle spawning works fine and I tested again through `/car`, `vehicleshop`, and `garage`  which they all use `ESX.CreateVehicle`, so if you are still facing issue I suggest you to do the same.
